### ISSUE TITLE
Allways making update in place for specific secrets

### ISSUE THREAD

**Issue by avivsalman** [DopplerHQ/terraform-provider-doppler#108]
Hi

i am using the doppler providerm and i have some 2 secrets that every apply making update in place even if something changed..

![image](https://github.com/user-attachments/assets/68d53ce3-1bbb-4810-a3c7-9a2da248cdf4)

the value of this secrets are private.key and public.key certs that i read from file, as attached here:

![image](https://github.com/user-attachments/assets/61ffef83-23da-4967-9692-8aba55d05cb3)

this is very important to me because every change in secrets trigreed kubernetes to restart the deployment..

Thanks :)

**Comment by avivsalman** [comment]
@watsonian thank you for your answer, i can confirm that nothing changed in doppler side, because we only edit from terraform.

i does it the same your are doing it in example 1, but i got an error, i can ensure that the problem is not in the way i handle it, because this 2 secrets are part of a lot of secrets, its happend only in this 2 secrets, the problem has to be connected to this specifig value, maybe because its from file, maybe the content are certificate string..

what else information i can share with you to solve this problem?



`

locals {
main_secrets = {
dev = {
            PRIVATE_KEY                    = file("../${path.module}/assets/secrets/oauth-private.key")
            PUBLIC_KEY                     = file("../${path.module}/assets/secrets/oauth-public.key")
}
}
}

    # create main dev secrets
    resource "doppler_secret" "main_secrets_dev" {
        depends_on = [doppler_environment.main_environment_dev]

        for_each = { for k, x in local.main_secrets.dev: k => x }

        project     = doppler_project.main.name
        config      = "dev"
        name        = each.key
        value       = each.value
    }
`

**Comment by watsonian** [comment]
Okay, I tried reproducing what you're doing more exactly and am still not seeing this issue:

```
terraform {
  required_providers {
    doppler = {
      source = "DopplerHQ/doppler"
    }
  }
}

variable "doppler_token" {
  type        = string
  description = "A token to authenticate with Doppler"
}

provider "doppler" {
  doppler_token = var.doppler_token
}

locals {
  main_secrets = {
    dev = {
      PRIVATE_KEY = file("../${path.module}/id_tftest")
      PUBLIC_KEY  = file("../${path.module}/id_tftest.pub")
    }
  }
}

resource "doppler_secret" "main_secrets_dev" {
  for_each = { for k, x in local.main_secrets.dev : k => x }

  project = "example"
  config  = "dev"
  name    = each.key
  value   = each.value
}
```

This is pretty bizarre. Would it be possible to delete those two secrets temporarily from your TF script, perform a terraform run to delete them in Doppler (double-check to make sure they're gone after this), then add them back in and run again so they're created again? If the problem continues persisting then, it has to be some nuance with the actual file contents. In that situation, could you open a support ticket at https://support.doppler.com and then we can continue investigating the problem there.

**Comment by avivsalman** [comment]
@watsonian thanks for trying helping me..

i found the solution after debuging the terraform output, i always send the certitificate with CRLF and doppler store it only with LF, so i changed the files to LF only and its worked.

Thanks :)
