### ISSUE TITLE
Cannot create multiple secrets

### ISSUE THREAD

**Issue by speekadievs** [DopplerHQ/terraform-provider-doppler#11]
Hello. Just started working with doppler but managed to hit a nasty bug. Every time I try to create multiple secret resources, they simply don't show up in the Doppler web UI. Here, for example, I have 11 secrets but running `terraform apply` only creates maybe 3 of them and always in some random order. Running `terraform apply` multiple times will actually create all the secrets eventually. 

Weirdly enough, If I declare them explicitly without the for_each loop and add dependencies for one another so that the secrets wouldn't be made in parallel, works fine

```
resource "random_password" "app_key" {
  length = 32
}

resource "random_password" "db_password" {
  length = 32
}

resource "random_password" "jwt_secret" {
  length = 32
}

resource "doppler_secret" "secret" {
  for_each = tomap({
    APP_KEY = random_password.app_key.result
    JWT_SECRET = random_password.jwt_secret.result

    HOST = "0.0.0.0"
    PORT = 3333
    CACHE_VIEWS = false

    DB_CONNECTION = "pg"

    PG_HOST = "postgresql"
    PG_PORT = 5432
    PG_USER = "root"
    PG_PASSWORD = random_password.db_password.result
    PG_DB_NAME = "crushtime"
  })
  project = "crushtime-api"
  config = "stg"
  name = each.key
  value = each.value
}
```

**Comment by nmanoogian** [comment]
Hi @speekadievs, thank you for sending this in!

You nailed it -- it's a problem with concurrent modification. We've got a fix in the works now (server-side) and I'll follow up here once it's shipped.

**Comment by nmanoogian** [comment]
@speekadievs We've shipped the fix! Can you give this another try and let me know if it behaves appropriately for you?
