### ISSUE TITLE
Allow environment branch creation

### ISSUE THREAD

**Issue by klyse** [DopplerHQ/terraform-provider-doppler#22]
Hi,

I was hoping to create a new Branch config with terraform. Equivalent of:
![Screenshot 2022-06-06 at 08 56 23](https://user-images.githubusercontent.com/10352866/172111073-9b488dfe-625d-442b-9e28-ea41285b43b7.png)

Here is my code: unfortunately this does not work because it creates a new environment with name `dev_frontend` instead of a branch `frontend` under `dev`:
```terraform
resource "doppler_environment" "frontend" {
  project = local.doppler_project
  slug = "${var.environment}_frontend"
  name = "Frontend"
}
```

I think this might not be supported at this point so I'd love to request this as a feature.

**Comment by klyse** [comment]
Ok, found out that this is a separate resource in terraform `doppler_config`.

```terraform
resource "doppler_config" "frontend" {
  project = doppler_project.frontend.name
  environment = var.environment
  name = "${var.environment }_github"
}
```

Closing this as this works as expected :) Wasn't obvious to me at first...

**Comment by nmanoogian** [comment]
Hi @klyse, thanks for filing this and I'm glad you got it working! I think the separation between environments and configs could be clearer in our Terraform docs; I'll see what we can do about improving that.

Thanks again and please keep the feedback coming!
