### ISSUE TITLE
Feature: Support kubernetes.io/tls instead of only Opaque

### ISSUE THREAD

**Issue by a-nldisr** [DopplerHQ/terraform-provider-doppler#25]
As I understand from the Kubernetes documentation the kubernetes.io/tls only difference is enforcing DER standards and that the key/cert is present. So consider this as a nice-to-have feature request. 

Current code only supports Opaque Kubernetes secrets. 
https://github.com/DopplerHQ/kubernetes-operator/blob/98ce8ccbefada12a4fa2ebff778f311059cbec5a/controllers/dopplersecret_controller_secrets.go#L196
Having the operator create kubernetes.io/tls when a certificate is present would be nice!

**Comment by nmanoogian** [comment]
Hi @a-nldisr! 👋 Did you mean to post this issue in our [kubernetes-operator](https://github.com/DopplerHQ/kubernetes-operator) repo?

**Comment by a-nldisr** [comment]
Oops! Yes, let me correct that!

**Comment by a-nldisr** [comment]
Closed and opened issue at right repo, sorry about this! 
https://github.com/DopplerHQ/kubernetes-operator/issues/25

**Comment by nmanoogian** [comment]
No problem!
