### ISSUE TITLE
ENHANCEMENT: Manage team members and access to projects

### ISSUE THREAD

**Issue by PeterMerkert** [DopplerHQ/terraform-provider-doppler#26]
I'd love to be able to add team members and their permissions using the Terraform provider (similar to the [Github collaborator](https://registry.terraform.io/providers/integrations/github/latest/docs/resources/repository_collaborator)), e.g.

```
data "doppler_collaborators" "petermerkert" {
  name = "peter.merkert@example.org"
  role = "Collaborator"
}

resource "doppler_projects_member" "project_membership" {
  project  = "my-project"
  name = data.doppler_collaborators.petermerkert.id
  role = "Collaborator"
  environments = ["Developmernt", "Testing"]
}
```

**Comment by nmanoogian** [comment]
Hey @PeterMerkert! Thanks for this suggestion -- we've gotten a few similar requests for managing users via Terraform recently and I appreciate that you wrote up how you'd expect the resources to look. I'll pass this along to our product team!

**Comment by guilhermedalmarco** [comment]
Is there any expectation to deliver this feature?

**Comment by nmanoogian** [comment]
Hi @guilhermedalmarco, this enhancement is absolutely still on our radar but we don't have a timeline for its delivery yet. I'll keep this issue up-to-date with any changes.

**Comment by ViacheslavKudinov** [comment]
Support of users in groups was added in [1.6.0](https://github.com/DopplerHQ/terraform-provider-doppler/releases/tag/v1.6.0)
granting access to the group on the project was added in [1.3.0](https://github.com/DopplerHQ/terraform-provider-doppler/releases/tag/v1.3.0)

**Comment by nmanoogian** [comment]
Thanks for following up here, @ViacheslavKudinov! [1.6.0](https://github.com/DopplerHQ/terraform-provider-doppler/releases/tag/v1.6.0) also added a user data source.

Closing this as complete but please feel free to reopen if there is additional functionality that y'all would like to see.
