### ISSUE TITLE
Resource creation fails with 

### ISSUE THREAD

**Issue by AnitaErnszt** [DopplerHQ/terraform-provider-doppler#27]
Hi Doppler team, 

we are using Doppler to create secrets via Terraform. Each project has around 30-40 secrets to create.
Occasionally the initial deployment (secret creation) fails with `context deadline exceeded (Client.Timeout exceeded while awaiting headers)` error. Subsequent runs work as expected.
Terroform is deployed via GitHub actions.

Please let me know if you need any further information. Thanks.

**Comment by nmanoogian** [comment]
Hi @AnitaErnszt, thanks for letting us know about this! We'll see about reproducing this issue and let you know what we find.

**Comment by nmanoogian** [comment]
@AnitaErnszt -- We just released v1.1.5 which adds automatic retries to protect against network errors like this. Thanks for letting us know about this issue!
