### ISSUE TITLE
QUESTION: Avoid resource replacement on new Secrets

### ISSUE THREAD

**Issue by guidodobboletta** [DopplerHQ/terraform-provider-doppler#28]
I have a usage question which I can't seem to be able to figure out. Last week I was using the provider to only query the secrets on our account by using the `doppler_secrets` data source

```
data "doppler_secrets" "test" { }
```

This week I wanted to not only grab the secrets from Doppler but manage them through Terraform too. So what I did was add a couple of `doppler_secret` resources:

```
resource "doppler_secret" "elasticsearch" {
  project = "test"
  config  = var.environment
  name    = "endpoint"
  value   = "https://${var.elasticsearch_domain}"
}
```

Previously I had an output to my Doppler module like this:

```
output "apollo_secrets" {
  description = "List of all Doppler test project secrets"
  sensitive   = true
  value       = data.doppler_secrets.test.map
}
```

Now when I try to manage Doppler secrets using Terraform apparently the data object gets changed in a way in which it tries to replace all resources that are using the secrets (eg: Aurora databases since it thinks we have a new username,password). 

Before this when we updated doppler secrets by hand on the website without using `doppler_secret` resources we didn't have this problem. Is there a way to solve this issue ? Is there a way to manage Doppler secrets and use the datasource without having Terraform think we're going to destroy everything?

**Comment by watsonian** [comment]
@guidodobboletta What you probably want to do here is reference the resource directly for any secrets you're managing inside Terraform rather than using the data source. For example:

```terraform
resource "doppler_secret" "elasticsearch" {
  project = "test"
  config  = var.environment
  name    = "endpoint"
  value   = "https://${var.elasticsearch_domain}"
}

output "apollo_secrets" {
  description = "List elasticsearch endpoint value"
  sensitive   = true
  value       = doppler_secret.elasticsearch.value
}
``

Then you can reference any secrets you aren't managing through Terraform (if there are any) using the data source:

```terraform
data "doppler_secrets" "test" {
  project = "test"
  config  = var.environment
}

output "doppler_managed_secret" {
  description = "something"
  sensitive = true
  value       = data.doppler_secrets.test.map.SOME_SECRET
}
```

Will that work for you?
