### ISSUE TITLE
Terraform CDK docs/examples

### ISSUE THREAD

**Issue by paymog** [DopplerHQ/terraform-provider-doppler#35]
It would be wonderful if there were some docs/examples on how to use the doppler provider with [Terraform CDK](https://github.com/hashicorp/terraform-cdk)

**Comment by nmanoogian** [comment]
Thanks for the recommendation, @paymog! I'll share this with our team.

**Comment by nmanoogian** [comment]
Hey @paymog -- thanks again for the recommendation! We've added [a guide](https://docs.doppler.com/docs/terraform-cdk) for how to use the Doppler Terraform provider with Terraform CDK and linked it to the README.
