### ISSUE TITLE
ENHANCEMENT: Support Doppler Service Accounts

### ISSUE THREAD

**Issue by ycabrer** [DopplerHQ/terraform-provider-doppler#50]
A new exciting feature was released by doppler to enable the use of service accounts. This is great really. I would like to be able to configure the same using terraform.

https://docs.doppler.com/docs/service-accounts

**Comment by nmanoogian** [comment]
Thanks for the recommendation, @ycabrer! This is definitely on our radar. I'll keep you posted here with any updates.

**Comment by a-nldisr** [comment]
> A new exciting feature was released by doppler to enable the use of service accounts. This is great really. I would like to be able to configure the same using terraform.

What are the limitations you are running into @ycabrer, i thought i could replace a personal token for this.

**Comment by nmanoogian** [comment]
Thank you for asking for clarification, @a-nldisr!

@ycabrer, I assumed that your feature request was to manage service accounts as resources in Terraform. To clarify, you can absolutely authenticate with the Doppler Terraform provider using a service account API token today.

**Comment by ycabrer** [comment]
@nmanoogian You are right about wanting to manage the resources! My perfect world would be to generate a unique service account token via terraform and use it when installing the doppler secret controller. 

At the moment I have a custom solution that generates 1 ephemeral read only service key for each config. It's working well but my account probably has a couple hundreds keys. I understand there is a hard upper limit to the amount of keys plus so eventually this will stop working for me.

**Comment by nmanoogian** [comment]
Perfect 👍 Service accounts would be excellent in that scenario. I'll keep you posted here when we have more developments on service-account-related Terraform resources.

**Comment by darren-recentive** [comment]
Hi @nmanoogian 👋 
Hope you're doing well, has there been any updates on the feature request?
Anything we can do to help?

**Comment by nmanoogian** [comment]
Thanks for following up, @darren-recentive! Nothing concrete to share on this feature yet but our team is working on backend APIs for managing Doppler service accounts, which is a prerequisite. I'll keep you posted here with any updates!

**Comment by Piccirello** [comment]
This was implemented in #57/

**Comment by darren-recentive** [comment]
Thank you @Piccirello!
