### ISSUE TITLE
What license is this released under?

### ISSUE THREAD

**Issue by srounce** [DopplerHQ/terraform-provider-doppler#54]
Which license is this provided under? I've made NixOS/nixpkgs#250556 but the question has been raised regarding which license this provider uses, as in my original commits for the PR I had assumed it was under MPL. If I could get some clarification it'd be much appreciated, thank you.

**Comment by nmanoogian** [comment]
Thanks for asking, @srounce, and thank you for adding that Nix package! This was definitely an oversight on our part. Our team is reviewing this PR currently to add a LICENSE file: #55

**Comment by srounce** [comment]
Lovely thank you very much, I'll update the Nixpkgs PR once that's merged.

**Comment by nmanoogian** [comment]
Merged! Thanks again for letting us know about this!

**Comment by srounce** [comment]
@nmanoogian Sorry to keep on at this, but would it be possible to cut another release with the license included as it doesn't apply retrospectively to already released versions.

**Comment by nmanoogian** [comment]
No worries! [terraform-provider-doppler v1.2.4](https://github.com/DopplerHQ/terraform-provider-doppler/releases/tag/v1.2.4) is now live with the updated license 👍
