### ISSUE TITLE
Feature: use multiple doppler providers with different doppler tokens

### ISSUE THREAD

**Issue by jason-curtis** [DopplerHQ/terraform-provider-doppler#58]
It may already be possible to do this, so this might just be an ask for some documentation!

My current terraform configuration needs to use secrets from multiple separate doppler projects via separate doppler tokens. Is there a recommended way to do that? I imagine you can use multiple provider configurations with different aliases, but I'm not clear on how the `data "doppler_secrets" "this" {}` block would refer to one or the other provider.

**Comment by watsonian** [comment]
@jason-curtis Ironically, I had a PR open to add examples of this to our README and it just fell along the wayside. Take a look and see if it helps. https://github.com/DopplerHQ/terraform-provider-doppler/pull/13

**Comment by jason-curtis** [comment]
I just saw that! thank you!
