### ISSUE TITLE
Feature Request: Manage Group Members for Groups

### ISSUE THREAD

**Issue by jeffchao** [DopplerHQ/terraform-provider-doppler#66]
You have a Doppler Terraform Provider which has a [`group` resource](https://registry.terraform.io/providers/DopplerHQ/doppler/latest/docs/resources/group). It would be nice to have the ability to manage (add/remove) users from a group. This would be useful for us to manage access to groups programmatically via Terraform.

**Comment by jeffchao** [comment]
Hey @nmanoogian! Great to hear you're working on this. Few comments.

Option 1 will be difficult on the user-end because we'd have to maintain a list of addresses which would easily get out of sync with the source of truth (Doppler). On the Doppler side, you'll have to add in extra validations because we (as the user) are essentially passing in arbitrary strings. This would be problematic for you because the DevEx would be worse because you'd probably have to do that validation on apply. For systems that do merge -> apply (such as Terraform Cloud and Spacelift), this would be bad. Then, if you want to do it on plan, then you'd have to modify your provider to make calls out to Doppler using some sort of hook.

I like Option 2 because it clarifies that the data source is a read-only thing which is managed by Doppler. In particular, as a user, I would create users via Doppler UI through invites and such, then if I want some automation via Terraform/IaC, I can query Doppler for my users. I also get a bit of validation via the data source which means I can also use my IDE autocompletion to help me write my configurations. Also as you pointed out, the re-adding/removing of user IDs might be an issue, particularly around audit functionality for Enterprise-y team management use cases.

**Comment by nmanoogian** [comment]
Awesome! Thanks for the detailed feedback, @jeffchao. I'll keep this issue updated with any developments 👍

**Comment by jeffchao** [comment]
Saw #72 . Thanks folks. Will take a look.

**Comment by nmanoogian** [comment]
Thanks again for your input on this, y'all! Please provide any feedback you may have on the new resources!

**Comment by jheimbuck** [comment]
@ViacheslavKudinov - tagging you here too and thanks for the input!
