### ISSUE TITLE
Feature: Add support of tags for `doppler_secrets_sync_aws_secrets_manager` (Resource)

### ISSUE THREAD

**Issue by ViacheslavKudinov** [DopplerHQ/terraform-provider-doppler#69]
Hi,
due to enforcing AWS tags in our organization, we need to have the support of tags on `doppler_secrets_sync_aws_secrets_manager` (Resource).

**Comment by nmanoogian** [comment]
Thanks for reporting this, @ViacheslavKudinov! Support for tags in the AWS Secrets Manager sync has been added in [v1.4.0](https://github.com/DopplerHQ/terraform-provider-doppler/releases/tag/v1.4.0) with PR #70.

It doesn't look like GitHub picked up your [magic word](https://github.com/DopplerHQ/terraform-provider-doppler/pull/70#issuecomment-1883597709) automatically so I'll go ahead and close this out manually!
