### ISSUE TITLE
Incorrect Usage Example

### ISSUE THREAD

**Issue by CalebDelbridge** [DopplerHQ/terraform-provider-doppler#7]
The usage example in the README states that you pass in your token via the `token` parameter, but in actuality, you pass it in through the `doppler_token` parameter. I suggest updating the example since it threw me off as to why terraform kept asking for the token other than that awesome provider can't wait for the ability to upsert secrets.

**Comment by nmanoogian** [comment]
Thanks @CalebDelbridge, good catch!
