### ISSUE TITLE
QUESTION: Is there a way to create service account API tokens after creating a service account?

### ISSUE THREAD

**Issue by cris-santos** [DopplerHQ/terraform-provider-doppler#80]
It's possible to create a service account with the `doppler_service_account,` but is there a way to create an API token for the service account? I couldn't find it in the documentation or the source code.

Having more specific documentation for the `workplace_permissions` param on the `doppler_service_account` resource would also be nice. I was able to get the actual values by making a request from the web app and inspecting the payload.

**Comment by watsonian** [comment]
@cris-santos There isn't currently an API for creating Service Account Tokens programmatically (and thus, not an option to do it via the Terraform provider either). We do have plans to add support for this though!

**Comment by cris-santos** [comment]
Hmm I see. Thank you!

**Comment by sebastiandero** [comment]
@cris-santos We at @magicproduct contributed this recently, fyi: https://github.com/DopplerHQ/terraform-provider-doppler/pull/86

**Comment by watsonian** [comment]
Yep, this functionality will be available in the next release (which should be coming out soon).

**Comment by watsonian** [comment]
Thanks @sebastiandero for your contribution, by the way! 😀
