### ISSUE TITLE
ENHANCEMENT: Expose `delete_from_target` for supported by provider syncs

### ISSUE THREAD

**Issue by ViacheslavKudinov** [DopplerHQ/terraform-provider-doppler#90]
Currently when termination of Terraform resources happens, secrets and "resources" will still remain on the target's side.

As it is supported by [REST AP](https://docs.doppler.com/reference/syncs-delete)I it will be great to expose for "users" of provider to be able to set `delete_from_target` when they decide it is safe to have this behavior.
Moreover it is the option on Doppler UI to keep or delete secrets on the target.

So, it will be great to get option to delete secrets of target. Maybe, can be set `false`  by default for the "safety".

**Comment by ViacheslavKudinov** [comment]
In some sense related to https://github.com/DopplerHQ/terraform-provider-doppler/issues/65 as well

**Comment by nmanoogian** [comment]
Thanks for the recommendation, @ViacheslavKudinov! Working on this now

**Comment by ViacheslavKudinov** [comment]
Hi,
i think it was addressed by this PR https://github.com/DopplerHQ/terraform-provider-doppler/pull/93
and is there sinse `v1.9.0`

**Comment by nmanoogian** [comment]
Right you are! I must have forgotten to add the "Closes" magic word to that PR. Thanks!
