### ISSUE TITLE
ENHANCEMENT: Ability to set custom secret's name (have full control of the name) for AWS Secrets Manager

### ISSUE THREAD

**Issue by ViacheslavKudinov** [DopplerHQ/terraform-provider-doppler#91]
Currently when we use resource `doppler_secrets_sync_aws_secrets_manager` it will always add `/doppler` suffix in the end of the name.

For example:

```hcl
resource "doppler_secrets_sync_aws_secrets_manager" "backend_prod" {
  integration = doppler_integration_aws_secrets_manager.prod.id
  project     = "backend"
  config      = "prd"

  region = "us-east-1"
  path   = "/backend/"
  tags   = { myTag = "enabled" }
} 
```
this example will create secret `backend/doppler` on AWS side.

We would like to have full control over how the secret's name will be on AWS Secrets Manager, as we have naming convention for all (when is possible) AWS resources at our company. 
It will be great if we could achieve full compatibility when we get secrets via Doppler.

**Comment by nmanoogian** [comment]
Thanks for the recommendation, @ViacheslavKudinov! I'll discuss this with the product team.

**Comment by ViacheslavKudinov** [comment]
Thank you.
We will test this version soon.
