### ISSUE TITLE
[QUESTION] How to activate config's _personal?

### ISSUE THREAD

**Issue by andtankian** [DopplerHQ/terraform-provider-doppler#95]
The `_personal` is a nice feature, how can we activate it using terraform?

**Comment by andtankian** [comment]
https://github.com/DopplerHQ/terraform-provider-doppler/pull/92

Just saw it.

**Comment by nmanoogian** [comment]
This was released in [v1.9.0](https://github.com/DopplerHQ/terraform-provider-doppler/releases/tag/v1.9.0) 👍 Please feel free to let us know if you run into any issues!
