### ISSUE TITLE
Submit signing key to OpenTofu registry

### ISSUE THREAD

**Issue by slaughtr** [DopplerHQ/terraform-provider-doppler#97]
Please consider submitting a signing key to the OpenTofu registry. I'm calling this out as it's something I've run into, and per the newest OpenTofu [release notes](https://opentofu.org/blog/opentofu-1-8-0/#an-ask-for-help-gpg-keys-for-providers) this is an easy thing to do that would ensure security for many users of the provider.

**Comment by nmanoogian** [comment]
Thanks so much for letting us know about this, @slaughtr! I've submitted our signing key here: https://github.com/opentofu/registry/issues/759
